version: "3.9"
services:
  web:
    build:
      context: ./typescript/simple-mercari-web
    depends_on:
      - app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:9000"
  app:
    build:
      context: .
      dockerfile: ./go/dockerfile
    ports:
      - "9000:9000"
    environment:
      FRONT_URL: "http://localhost:3000"

