# syntax=docker/dockerfile:1

FROM golang:1.21.7-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY db/ ./db/
COPY go/ ./go/

WORKDIR /app/go

RUN go mod download
RUN go build -o ./mercari-build-training ./app/*.go

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /app

USER trainee

EXPOSE 9000

CMD [ "/app/go/mercari-build-training" ]
