# syntax=docker/dockerfile:1

FROM node:20-alpine

WORKDIR /web

COPY public/ ./public/
COPY src/ ./src/
COPY package*.json ./
COPY tsconfig.json ./

RUN npm ci

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /web

USER trainee

EXPOSE 3000

CMD [ "npm", "start" ]